# Generated by Django 2.0.3 on 2018-03-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180325_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_time',)},
        ),
    ]
