# Generated by Django 2.0.3 on 2018-04-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='0', max_length=2)),
                ('isDo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(default='', max_length=100)),
                ('hum', models.FloatField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('pm2_5', models.FloatField(default=0)),
                ('hcho', models.FloatField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Device')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=8)),
                ('user_age', models.CharField(default='10', max_length=3)),
                ('user_sex', models.BooleanField(default=True)),
                ('user_email', models.CharField(default='default@django.com', max_length=100)),
                ('user_address', models.CharField(default='', max_length=50)),
                ('user_city', models.CharField(default='', max_length=60)),
                ('user_state_province', models.CharField(default='', max_length=30)),
                ('user_country', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testTime', models.DateTimeField(auto_now_add=True)),
                ('testMessage', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='dev_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProUser'),
        ),
    ]
