# Generated by Django 2.0.3 on 2018-05-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prouser_userlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='devTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ProUser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Device'),
        ),
    ]
