# Generated by Django 2.0.3 on 2018-05-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180501_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='devId',
            field=models.CharField(default='12345', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='devTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DEVSN', to='api.ProUser'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.Device'),
        ),
    ]
