# Generated by Django 2.0.3 on 2018-05-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180518_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='device_control',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviceControl', to='api.Device'),
        ),
    ]
